[platformio]
default_envs = esp32_dynamixel

[env:esp32_dynamixel]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  https://github.com/ROBOTIS-GIT/Dynamixel2Arduino.git#0.8.1
