[platformio]
default_envs = esp32_dynamixel

[env:esp32_dynamixel]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  https://github.com/ROBOTIS-GIT/Dynamixel2Arduino.git#0.8.1
build_flags =
  -D MOTOR_BACKEND_DYNAMIXEL=1

[env:arduino_uno_servo]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps =
  arduino-libraries/Servo@^1.2.2
build_flags =
  -D MOTOR_BACKEND_SERVO=1
